package com.finpay.auth.entity;

import java.time.Instant;
import java.util.EnumSet;
import java.util.Set;
import java.util.UUID;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

/**
 * An authenticatable identity.
 *
 * <p>This service owns identity and authentication only. A person's name, address and anything
 * else describing them belongs to the user service; holding it here too would create two sources
 * of truth for the same fact.
 *
 * <p>The password is deliberately not on this entity. It lives on {@link Credential}, so loading a
 * user never implicitly drags a password hash into memory or into a log line.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Assigned by the application rather than generated by the database.
     *
     * <p>The identifier appears in URLs and in events, so it is a UUID: a sequential integer would
     * leak how many accounts exist and let a caller enumerate other users by guessing.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Stored lower-cased and uniquely constrained. Two accounts differing only in case would let
     * one person take another's sign-in identifier, so normalisation happens before persistence
     * and the database refuses anything else.
     */
    @Column(name = "email", nullable = false, length = 320)
    private String email;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    private UserStatus status;

    @Column(name = "email_verified", nullable = false)
    private boolean emailVerified;

    @Column(name = "failed_login_attempts", nullable = false)
    private int failedLoginAttempts;

    @Column(name = "locked_until")
    private Instant lockedUntil;

    @Column(name = "last_login_at")
    private Instant lastLoginAt;

    /**
     * Roles held by this user.
     *
     * <p>Eagerly fetched because there are at most four and every authorization decision needs
     * them; a lazy collection here would only trade a join for an N+1.
     *
     * <p>{@code granted_at} is left to the database default rather than mapped: nothing in the
     * application reads it yet, and mapping a column merely to ignore it invites drift.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 32)
    private Set<Role> roles = EnumSet.noneOf(Role.class);

    /**
     * Maintained by a database trigger, so a row changed by a migration or by psql is still
     * correct. Mapped read-only to keep the application from disagreeing with it.
     */
    @Column(name = "created_at", insertable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", insertable = false, updatable = false)
    private Instant updatedAt;

    /**
     * Optimistic locking. Null on a new instance, which is also how Hibernate recognises that an
     * entity with an application-assigned id is new and needs an insert rather than a select.
     */
    @Version
    @Column(name = "version")
    private Long version;

    protected User() {
        // for JPA
    }

    private User(UUID id, String email, UserStatus status, Set<Role> roles) {
        this.id = id;
        this.email = email;
        this.status = status;
        this.roles = roles;
    }

    /**
     * Creates a newly registered user.
     *
     * <p>Starts {@link UserStatus#PENDING_VERIFICATION} with the {@link Role#USER} role. The email
     * must already be normalised; this constructor does not silently repair it, because a value
     * that reached here un-normalised means a caller skipped a step.
     */
    public static User register(String normalisedEmail) {
        return new User(UUID.randomUUID(), normalisedEmail, UserStatus.PENDING_VERIFICATION, EnumSet.of(Role.USER));
    }

    public UUID getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public UserStatus getStatus() {
        return status;
    }

    public boolean isEmailVerified() {
        return emailVerified;
    }

    public int getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    public Instant getLockedUntil() {
        return lockedUntil;
    }

    public Instant getLastLoginAt() {
        return lastLoginAt;
    }

    public Set<Role> getRoles() {
        return Set.copyOf(roles);
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public Long getVersion() {
        return version;
    }

    /**
     * Identity is the assigned id. Deliberately not using email: it is unique, but an entity's
     * equality must not change if a user ever changes their address.
     */
    @Override
    public boolean equals(Object other) {
        return other instanceof User user && id != null && id.equals(user.id);
    }

    @Override
    public int hashCode() {
        return User.class.hashCode();
    }

    /** Never includes the email: this string reaches logs, and the address is personal data. */
    @Override
    public String toString() {
        return "User[id=%s, status=%s]".formatted(id, status);
    }
}
